name = "structure4b"
account_id = "63913da2f930251ebbbf2dcb940b90dc"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

main = "dist/_worker.js"

[build]
command = "npm run build"